version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: micro-app
    image: junimhs/micro-php
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - micro-network

  nginx:
    image: nginx:latest
    container_name: micro-nginx
    ports:
      - "8080:80"
      - "445:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - micro-network

networks:
  micro-network:
      driver: bridge
